// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrHRiEEO09B353YMxNsyJo2vmfxXlxlvk',
    appId: '1:973582339517:web:3a54477e1e6e6cadd196d4',
    messagingSenderId: '973582339517',
    projectId: 'mobile-boxing',
    authDomain: 'mobile-boxing.firebaseapp.com',
    storageBucket: 'mobile-boxing.appspot.com',
    measurementId: 'G-SWGDQZ4Y9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbl2LjvcvRZzKudhccGFXKlLYTqYv1IHM',
    appId: '1:973582339517:android:741048f65d4ed3fdd196d4',
    messagingSenderId: '973582339517',
    projectId: 'mobile-boxing',
    storageBucket: 'mobile-boxing.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmfUyfPEEkAzE7bB1nRmqMNUqcqtQLqUI',
    appId: '1:973582339517:ios:534f0ddab9958aa8d196d4',
    messagingSenderId: '973582339517',
    projectId: 'mobile-boxing',
    storageBucket: 'mobile-boxing.appspot.com',
    iosBundleId: 'com.example.boxingCampApp',
  );
}
